# Generated by Django 5.0.8 on 2024-08-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Introduction')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Role')),
                ('paragraph', models.TextField(blank=True, null=True, verbose_name='Introduction')),
                ('avatar_img', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id')),
                ('HireMe_link', models.CharField(blank=True, max_length=100, null=True)),
                ('Resume_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Heros Section',
            },
        ),
    ]
