# Generated by Django 5.0.8 on 2024-08-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeDetails',
            new_name='Homepage',
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Homepage Section'},
        ),
    ]
