# Generated by Django 5.0.8 on 2024-08-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_rename_homedetails_homepage_alter_homepage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(blank=True, max_length=100)),
                ('subheading', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
