# Generated by Django 5.0.8 on 2024-08-09 12:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Me'},
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Breif Explanation about yourself'),
        ),
    ]
