# Generated by Django 5.0.8 on 2024-08-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0005_languagesicons_mycontact_project_servicesoffred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesicons',
            name='exp_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=200, verbose_name='Experience Level'),
        ),
    ]
