# Generated by Django 5.1 on 2024-08-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0006_alter_languagesicons_exp_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_link',
            new_name='video_link',
        ),
    ]
